apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector-similarity-search-deployment
  labels:
    app: vector-similarity-search
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vector-similarity-search
  template:
    metadata:
      labels:
        app: vector-similarity-search
    spec:
      containers:
      - name: vector-similarity-search
        image: chukwuebukacihuoma/vector-similarity-search:latest
        ports:
        - containerPort: 8001   # Port the app is running on
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"










