apiVersion: v1
kind: Service
metadata:
  name: similarity-search-service
spec:
  selector:
    app: similarity-search
    app.kubernetes.io/name: similarity-search
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Use NodePort for local, LoadBalancer for cloud environments
